name: Deploy

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: 'Build'
        env:
          COSMIC_BUCKET_SLUG: ${{ secrets.COSMIC_BUCKET_SLUG }}
          COSMIC_READ_KEY: ${{ secrets.COSMIC_READ_KEY }}
          GITHUB_API_KEY: ${{ secrets.GH_API_KEY }}
        run: npm run build  
      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GH_API_KEY }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: 'out_publish'
          functions-dir: 'out_functions'  
